default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.db

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5